### ISSUE TITLE
Problems setting up Library

### ISSUE THREAD

**Issue by nicolas-goudry** [nytimes/library#12]
Hello,

I tried to setup Library for my organisation, but I’m facing an error that I don’t understand.

Here are the steps I took :
1. Create a shared folder under my account (managed by my organisation)
2. Create a project under my organisation
3. Operations on GCP :
   1. Enable Google Drive API
   2. Enable Cloud Datastore *in Datastore mode* (nothing about mode is specified in `README.md`)
   3. Create a service account with Cloud Datastore User role (and get cred JSON file)
   4. Create oAuth credentials with consent screen
4. Operations on local environment :
   1. Cloned repo
   2. Installed dependencies (`npm i --no-optional`)
   3. Copy oAuth cred JSON file to `server/.auth.json`
   4. Setup `.env` file with :
      * NODE_ENV : `development`
      * GOOGLE_CLIENT_ID : client id from oAuth cred
      * GOOGLE_CLIENT_SECRET : client secret from oAuth cred
      * GCP_PROJECT_ID : created project ID
      * APPROVED_DOMAINS : same as approved domains set for oAuth credentials
      * SESSION_SECRET : generated with `node -e "console.log(require('crypto').randomBytes(256).toString('base64'));"`
      * DRIVE_TYPE : set to `folder`
      * DRIVE_ID : created folder ID

After I took those steps, I launched project with `npm run build && npm run watch` and navigated to `http://localhost:3000`.

I directly got a `500` error and this is logged in terminal :
```javascript
{ message:
[0]    '9 FAILED_PRECONDITION: no matching index found. recommended index is:\n- kind: LibraryViewTeam\n  properties:\n  - name: userId\n  - name: lastViewedAt\n    direction: desc\n',
[0]   stack:
[0]    'Error: 9 FAILED_PRECONDITION: no matching index found. recommended index is:\n- kind: LibraryViewTeam\n  properties:\n  - name: userId\n  - name: lastViewedAt\n    direction: desc\n\n    at Object.exports.createStatusError (/home/nicolas/dev/yellow/library/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/home/nicolas/dev/yellow/library/node_modules/grpc/src/client_interceptors.js:1204:28)\n    at InterceptingListener._callNext (/home/nicolas/dev/yellow/library/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/home/nicolas/dev/yellow/library/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/home/nicolas/dev/yellow/library/node_modules/grpc/src/client_interceptors.js:845:24)',
[0]   code: 9,
[0]   metadata: { _internal_repr: {} },
[0]   details:
[0]    'no matching index found. recommended index is:\n- kind: LibraryViewTeam\n  properties:\n  - name: userId\n  - name: lastViewedAt\n    direction: desc\n',
[0]   note:
[0]    'Exception occurred in retry method that was not classified as transient' }
```

I can’t find where I’m wrong setting up Library... Can you please help me ?

Thanks in advance.

**Comment by isaacwhite** [comment]
Hey @nicolas-goudry, the stack trace that you provided is likely unrelated to the 500. 

It's not mentioned in your issue description: did you share the folder you created with the service account email that you got from the service account JSON file? Lack of access is the most likely reason for receiving a 500, followed by an error generating the site structure if your shared folder is empty. I'd recommend [the steps listed on the demo site](https://nyt-library-demo.herokuapp.com/get-started) in sequence, if you haven't already.

The specific trace you mentioned is printed when [Cloud Datastore indices have not been configured](https://nyt-library-demo.herokuapp.com/get-started/enable-and-configure-api-services), but it only blocks reading history operations, not rendering the site itself. Do you see another stack trace printed in addition to that one?

**Comment by namdau** [comment]
You might missed this step of creating the indexes:
```
gcloud datastore indexes create ./config/index.yaml --project YOUR_PROJECT_ID_HERE
```

**Comment by nicolas-goudry** [comment]
@isaacwhite Oh my… Sorry, I missed this step. I thought that if the service account was created under my organisation, it would get access to folders shared to this org, but now I guess it only works this way with team drives?

Also, I was missing the indexes creation step, thanks @namdau
