### ISSUE TITLE
Unexpected token in JSON error on current master commit d8a2c447

### ISSUE THREAD

**Issue by madsenibis** [nytimes/library#14]
I followed the detailed instructions in the getting started pages (and looked at issue #12.  APIs are enabled, oAuth2 tokens created, datastore indexes created, service account, etc.  

I have one file only in my drive folder, and the drive ID is correct.  When I run locally with `npm run watch`, I get the following:

[0] debug: updating tree...
[0] warn: failed updating tree
[0] { message: 'Unexpected token \' in JSON at position 0',
[0]   stack: 'SyntaxError: Unexpected token \' in JSON at position 0\nSyntaxError: Unexpected token \' in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at ReadStream.inputStream.setEncoding.on.on.on (/Users/mark/ibis/devel/src/internal-documentation/library/node_modules/google-auth-library/build/src/auth/googleauth.js:346:39)\n    at ReadStream.emit (events.js:164:20)\n    at endReadableNT (_stream_readable.js:1062:12)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\nFrom previous event:\n    at /Users/mark/ibis/devel/src/internal-documentation/library/node_modules/promise-inflight/inflight.js:29:16\n    at _inflight (/Users/mark/ibis/devel/src/internal-documentation/library/node_modules/promise-inflight/inflight.js:28:25)\n    at /Users/mark/ibis/devel/src/internal-documentation/library/node_modules/promise-inflight/inflight.js:22:14\n    at runCallback (timers.js:773:18)\n    at tryOnImmediate (timers.js:734:5)\n    at processImmediate [as _immediateCallback] (timers.js:711:5)\nFrom previous event:\n    at inflight (/Users/mark/ibis/devel/src/internal-documentation/library/node_modules/promise-inflight/inflight.js:14:40)\n    at updateTree (/Users/mark/ibis/devel/src/internal-documentation/library/server/list.js:66:10)\n    at startTreeRefresh (/Users/mark/ibis/devel/src/internal-documentation/library/server/list.js:372:11)\n    at Timeout.setTimeout [as _onTimeout] (/Users/mark/ibis/devel/src/internal-documentation/library/server/list.js:378:22)\n    at ontimeout (timers.js:466:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)',
[0]   __stackCleaned__: true }

Is this is a known issue in the code, or an indication that I set up authentication wrong?  Please help!

**Comment by isaacwhite** [comment]
Hi @madsenibis, the JSON parse that needs to happen before you can list the contents of the drive relates to the service account JSON that needs to be present either as an environment variable or in a local `.auth.json`. Are you providing that as a file or through an env var? In the env var case, you'll need to make sure that new lines are stripped from the service account JSON in your `.env` file.

**Comment by madsenibis** [comment]
Thank you - yep, there was a newline at the end of the local `.auth.json`.  Appreciate the help, and thank you very much for open sourcing this project - it is so handy to give our teams a way to build documentation via Google Docs!
