### ISSUE TITLE
Server error serving main page

### ISSUE THREAD

**Issue by infojunkie** [nytimes/library#17]
### Context (Environment)
Heroku deployment

### Expected Behavior
Open app front page

### Actual Behavior
Server error reported. Heroku log showing:
```
error: Serving an error page for / 
2019-04-15T18:45:58.064071+00:00 app[web.1]: { message: 'Cannot convert undefined or null to object',
2019-04-15T18:45:58.064074+00:00 app[web.1]:   stack:
2019-04-15T18:45:58.064084+00:00 app[web.1]:    'TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at buildDisplayCategories (/app/server/routes/pages.js:56:29)\n    at handlePage (/app/server/routes/pages.js:47:24)' }
```

### To Reproduce
Navigate to front page.

### Additional Information
I've tried my best to follow the steps for Heroku deployment. I got as far as `gcloud datastore indexes create ./index.yaml --project your-gcp-project-here` which is only documented in the yaml file itself.

Happy to supply config info on Google Cloud and/or Heroku as needed.

**Comment by isaacwhite** [comment]
Hey @infojunkie, you might encounter this error if there are no files in the drive Library is pointed at. Can you confirm based on the logs if any data is successfully retrieved from the drive?

**Comment by infojunkie** [comment]
Sorry, we've moved away from trying your system. I will not be able to supply you with the needed info.
