### ISSUE TITLE
`res` undefined for some `handleRedirect` calls?

### ISSUE THREAD

**Issue by afischer** [nytimes/library#313]
### Context (Environment)

Running a dockerized Library instance with a team drive. Additionally, we have some custom cache logic.

Occasionally, we're seeing 500s on redirects, with the following error:

```
error: Serving an error page for /newsroom-knowledge/seo
{
  message: "Cannot read property 'redirect' of undefined",
  stack: "TypeError: Cannot read property 'redirect' of undefined\n" +
    "at handleRedirects (/usr/src/app/server/routes/redirects.js:15:15)\n" +
    "at runMicrotasks (<anonymous>)\n" +
    "at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```

This implies the `res` object in `handleRedirects` is undefined.

### Expected Behavior
Redirects work as expected

### Actual Behavior

The page 500s

### To Reproduce
Unclear at this point!

**Comment by afischer** [comment]
This issue has to do with our custom cache logic, and is not applicable to the core repo here. Closing.
