### ISSUE TITLE
Server error 500 after deploying site to Google App Engine

### ISSUE THREAD

**Issue by magicustwo** [nytimes/library#38]
### Context (Environment)

Google App Engine Deployment
Node v9.0.0

### Expected Behavior
After running `gcloud app deploy --project=**my_project_id**`
and then
`gcloud app browse --project=**my_project_id**`
I should be able to browse my library site.

### Actual Behavior

After running `gcloud app deploy --project=**my_project_id**`
and then
`gcloud app browse --project=**my_project_id**`
I'm asked to sign into my library site. After signing in with my account, I'm presented with the following error:
![Screenshot 2019-06-10 at 16 08 47](https://user-images.githubusercontent.com/4963677/59275473-48eace00-8c54-11e9-9a56-7b1032c42e55.png)

### To Reproduce

Follow steps as written on the following guides in the following order:
1. https://nyt-library-demo.herokuapp.com/get-started/create-a-google-cloud-platform-project
2. https://nyt-library-demo.herokuapp.com/get-started/create-a-service-account
3. https://nyt-library-demo.herokuapp.com/get-started/enable-and-configure-api-services
4. https://nyt-library-demo.herokuapp.com/get-started/create-an-oauth-client
5. https://nyt-library-demo.herokuapp.com/get-started/deploying-library-google-app-engine

### Additional Information
Seems to be the same problem as explained here: https://github.com/nytimes/library/issues/17. Full disclosure, I'm not experienced in doing this sort of thing, and am unsure of even where to start troubleshooting this problem! I have noticed some small discrepancies between the steps I followed (from the sample NYT Library [here](https://nyt-library-demo.herokuapp.com/get-started/deploying-library-google-app-engine)) and the steps as they are listed here on GitHub: https://github.com/nytimes/library#deploying-the-app (e.g. the `NODE_ENV=development # node environment` line in step 4 of Development Workflow.

### Possible Solution

I've been through all the steps a few times, maybe I just need to start again and stick to the instructions as they appear on GitHub?

**Comment by isaacwhite** [comment]
Hey @magicustwo, are you able to view the server logs for your app engine deployment? Without a stack trace from the 500 it's hard to say what specific problem you might be running into as that screen is a catch-all for any unexpected error.

**Comment by magicustwo** [comment]
Hey @isaacwhite, thanks for the speedy reply! So I've just run `gcloud app logs read` (thanks Google) and this is what the log says: 

> 2019-06-11 14:46:14 default[20190611t135450]  info: Trying to parse client credentials via GOOGLE_APPLICATION_JSON.
2019-06-11 14:46:14 default[20190611t135450]  warn: failed updating tree
2019-06-11 14:46:14 default[20190611t135450]  { message: 'Unexpected end of JSON input',
2019-06-11 14:46:14 default[20190611t135450]    stack:
2019-06-11 14:46:14 default[20190611t135450]     'SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at inflight (/srv/server/auth.js:33:25)\n    at /srv/node_modules/promise-inflight/inflight.js:29:24\n    at Promise._execute (/srv/node_modules/bluebird/js/release/debuggability.js:303:9)\n    at Promise._resolveFromExecutor (/srv/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/srv/node_modules/bluebird/js/release/promise.js:79:10)\n    at _inflight (/srv/node_modules/promise-inflight/inflight.js:28:25)\n    at /srv/node_modules/promise-inflight/inflight.js:22:14\n    at tryCatcher (/srv/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/srv/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/srv/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/srv/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async._drainQueue (/srv/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/srv/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/srv/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)' }

I guess I've messed up adding the JSON to my .env file? I'll go back and check I don't have an apostrophe or bracket where there shouldn't be one.

I'll keep you posted!

**Comment by magicustwo** [comment]
Hey @isaacwhite, the source of all my problems was line breaks in the GOOGLE_APPLICATION_JSON part of the .env.

Went through it all to make sure it was just on one line and presto! I have a functional library deployment now!

Such a rookie mistake 😅 , but thanks for the nudge in the right direction!
